name: draft_view
description: A draft js renderer written in Dart! You can easily render your draft js object in Flutter!
version: 1.0.0
repository: https://github.com/sirily11/flutter_draftview

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  tuple: ^2.0.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^3.0.1

flutter:
  